### ISSUE TITLE
Apakah template ini bisa dipakai buat tesis S2?

### ISSUE THREAD

**Issue by Abidzar16** [petrabarus/if-itb-latex#12]
Jika tidak bisa bisa, apakah ada konfigurasi yang harus diubah ditemplatenya atau ada alternatif lain? Terima kasih

**Comment by petrabarus** [comment]
Halooo, saya pakenya buat tesis S2 juga kokk

**Comment by Abidzar16** [comment]
Baik, masalahnya pas saya cek template latexnya, agak sedikit berbeda dengan yang diberikan oleh ITB

Referensi template tesis: https://sps.itb.ac.id/pedoman-tesis-dan-disertasi/#1659414944423-5c08f698-26df
